### ISSUE TITLE
(Re)-using property definitions results in Cypher scripts with duplicate create constraint statements

### ISSUE THREAD

**Issue by wouterroos** [hackolade/neo4j#24]
Hi,

I'm modelling a neo4j graph in Hackolade and I'm running into an issue that when you re-use a Definition (in this case for a property key) which has a unique constraint it results in a Cypher script that has a create constraint statement for each time the definition is used. This leads to errors when executing the script on a neo4j database. I'm new to both Hackolade and neo4j so I might be missing something. 

Any help would be greatly appreciated!

**Comment by pdesmarets** [comment]
In the way it is implemented, the basic principle of a definition is that literally all of its properties are used where referenced, including the Unique property if enabled.  If you want to deviate from that behavior, wouldn't a workaround be to have 2 definitions: one with Unique checked, and one with Unique unchecked?

**Comment by wouterroos** [comment]
@pdesmarets I'd actually want all references of the definition to have the unique key constraint, so based on your comment I'd assume my usage of the definition is correct. The problem however is that neo4j doesn't accept duplicate create constraints in Cypher scripts, which is what seems to be produced by hackolade:

![image](https://user-images.githubusercontent.com/5137829/152765173-3d04db62-db33-431d-9428-beda31550624.png)

**Comment by pdesmarets** [comment]
OK, I see your point.  Thanks for the visuals!  I'll have the team look into it.  I'll keep you posted.

**Comment by pdesmarets** [comment]
One more question for you. The IF [NOT] EXISTS syntax for constraints is only available in Neo4j 4.1.3 and onwards.  What version are you running?

**Comment by wouterroos** [comment]
> The IF [NOT] EXISTS syntax for constraints is only available in Neo4j 4.1.3 and onwards. What version are you running?

Yes indeed, I read that somewhere. I'm running neo4j 4.4.3 and created my model using the 4.3 target version in Hackolade.

![image](https://user-images.githubusercontent.com/5137829/152770407-7ee057d0-633a-4de9-b26f-38888bb687ab.png)

Perhaps Hackolade's Cypher generation logic should be changed for 4.3?

**Comment by pdesmarets** [comment]
Indeed.  I'll keep you posted.

**Comment by wouterroos** [comment]
@pdesmarets Thanks, I just gave it a quick try and it seems to work great!
